### ISSUE TITLE
List of Countries - USA

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#113]
Please remove the "(the)" at the end of the USA - United States of America

![image](https://user-images.githubusercontent.com/26025574/95685982-73a7b680-0bfb-11eb-89a5-bc239f3d44f2.png)

**Comment by Melvin-Thomas-Dev** [comment]
Done

**Comment by Melvin-Thomas-Dev** [comment]
There were few other country names that had the same problem. I have removed all of them.
I took the list from the internet and hadn't checked all the country names myself.
I have changed them now.

**Comment by heldyboy** [comment]
Is this really fixed?  Maybe the latest version is not pushed to the production server, however I still see the issue.

**Comment by Melvin-Thomas-Dev** [comment]
Is this the live website? Or is this from the develop branch?
I pushed it to the develop branch.
The master branch is deployed to production right?

**Comment by heldyboy** [comment]
Sorry Melvin, you are correct.  I pulled down the new one, and it looks good.  Thanks.
